#!/usr/bin/env python
import os

Import("env")
Import("env_modules")

env_src = env_modules.Clone()
sources = []

# 搜索当前目录下所有.cpp文件
for root, dirs, files in os.walk('.'):
    for f in files:
        if f.endswith('.cpp'):
            sources.append(root + '/' + f)

# Godot source files
env_src.add_source_files(env.modules_sources, sources)